# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(through='ykea.ItemCnt', to='ykea.Item')),
            ],
        ),
        migrations.AddField(
            model_name='itemcnt',
            name='sCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Shoppingcart'),
        ),
    ]
