# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0002_auto_20180426_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcnt',
            old_name='Item',
            new_name='itemId',
        ),
        migrations.RenameField(
            model_name='itemcnt',
            old_name='sCart',
            new_name='sCartId',
        ),
        migrations.RemoveField(
            model_name='itemcnt',
            name='count',
        ),
    ]
