# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0004_itemcnt_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcnt',
            name='count',
        ),
    ]
