# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0005_remove_itemcnt_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcnt',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
