# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0006_itemcnt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcnt',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
