# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0011_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured_photo',
            field=models.ImageField(upload_to='staticfiles'),
        ),
    ]
