# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ykea', '0012_auto_20180525_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
