# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ykea', '0013_itemhist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemhist',
            name='user',
        ),
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(through='ykea.ItemHist', to='ykea.Item'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemhist',
            name='billId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ykea.Bill'),
            preserve_default=False,
        ),
    ]
